### ISSUE TITLE
Policy with root-level wildcard resource isn't being honored when forward slash is used

### ISSUE THREAD

**Issue by jasonatepaint** [roggervalf/iam-policies#18]
It's unclear from the examples and the source code tests if paths with a forward slash should honor a wildcard. 

Example of a super user (AWS IAM administrator access)
```
const allowExample = new IdentityBasedPolicy([
       {
		effect: 'allow',
		action: ['*'],
		resource: ['*'],
	}
]);

can = allowExample.evaluate({
	action: 'read',
	resource: 'org:123:999/image'
});

//returns false
```

The only way to make the above statement to be true is to add an additional wildcard resource with the pathing:
```
const allowExample = new IdentityBasedPolicy([
	{
		effect: 'allow',
		action: ['*'],
		resource: ['*', '*/*' ],
	}
]);

//returns true
```

This would require those additional wildcard resources are added anytime another level of pathing is added to a resource.

Is there a reason for the special handling of the forward slash?   It would seem a root-level wildcard of * should allow all resources, regardless of path.

Thanks!

**Comment by roggervalf** [comment]
Hi @jasonatepaint, thanks for notice this, already fix it and add your example. Let try the new realease.
